use std::collections::BTreeMap;

use time::OffsetDateTime;
use url::Url;

use crate::key::ObjKey;

/// Input required to allocate one object version.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ObjSlotSpec<'a> {
    /// Stable business-object identifier.
    pub id: &'a str,
    /// Opaque content hash.
    pub hash: &'a [u8],
    /// Validated object suffix.
    pub ext: &'a str,
    /// Media type signed into the upload capability.
    pub content_type: &'a str,
    /// Exact signed byte length.
    pub byte_len: u64,
}

/// Upload capability returned by `ObjDept`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObjSlot {
    /// Allocated logical object key.
    pub key: ObjKey,
    /// Signed upload URL.
    pub url: Url,
    /// Headers signed into the capability.
    pub headers: BTreeMap<String, String>,
    /// Capability expiry.
    pub expires_at: OffsetDateTime,
}

/// Storage-neutral upload capability generated by an object pool.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObjPoolSlot {
    /// Signed upload URL.
    pub url: Url,
    /// Headers signed into the capability.
    pub headers: BTreeMap<String, String>,
    /// Capability expiry.
    pub expires_at: OffsetDateTime,
}
