use std::collections::BTreeMap;

use time::OffsetDateTime;
use url::Url;

use crate::key::{KeyMap, ObjKey};

/// Input required to allocate one object version.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObjSlotSpec<'a, K>
where
    K: KeyMap,
{
    /// Typed business identity from which the physical key is derived.
    pub dom: K::Dom,

    /// Opaque content hash.
    pub hash: &'a [u8],

    /// Media type signed into the upload capability.
    pub content_type: &'a str,

    /// Exact signed byte length.
    pub byte_len: u64,
}

/// Upload capability returned by `ObjDept`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObjSlot {
    //
    /// Allocated logical object key.
    pub key: ObjKey,
    /// Signed upload URL.
    pub url: Url,
    /// Headers signed into the capability.
    pub headers: BTreeMap<String, String>,
    /// Capability expiry.
    pub expires_at: OffsetDateTime,
}

/// Storage-neutral upload capability generated by an object pool.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObjPoolSlot {
    //
    /// Signed upload URL.
    pub url: Url,
    /// Headers signed into the capability.
    pub headers: BTreeMap<String, String>,
    /// Capability expiry.
    pub expires_at: OffsetDateTime,
}
