// LEGACY DISABLED: Do not use. This file is intentionally commented out.
// pub mod local_message;
// pub mod member;
// pub mod member_invitation;
// pub mod system_mail;
// pub mod team;
// pub mod user;
// pub mod workset;
// 
// use async_trait::async_trait;
// use futures_util::future::BoxFuture;
// 
// use poprako_macro::forward_ref_super;
// 
// use crate::ForwardRef;
// 
// use crate::domain::repo_legacy::local_message::{
//     LocalMessageQuery, LocalMessageRepoTransactional,
// };
// use crate::domain::repo_legacy::member::{MemberRepo, MemberRepoTransactional};
// use crate::domain::repo_legacy::member_invitation::MemberInvitationRepoTransactional;
// use crate::domain::repo_legacy::system_mail::{SystemMailQuery, SystemMailRepoForward};
// use crate::domain::repo_legacy::team::{TeamRepo, TeamRepoForward, TeamRepoTransactional};
// use crate::domain::repo_legacy::user::{UserRepo, UserRepoForward, UserRepoTransactional};
// use crate::domain::repo_legacy::workset::{
//     WorksetRepo, WorksetRepoForward, WorksetRepoTransactional,
// };
// use crate::domain::result::DomainResult;
// 
// // Import forward markers for composite sub-traits so the blanket ForwardRef
// // bridge impls generated by #[forward_ref_super] can resolve them.
// use crate::domain::repo_legacy::local_message::LocalMessageRepoForward;
// use crate::domain::repo_legacy::member::MemberRepoForward;
// 
// /// Composite read-only repo contract for non-transactional use cases.
// #[forward_ref_super]
// pub trait Repo:
//     UserRepo + TeamRepo + SystemMailQuery + WorksetRepo + MemberRepo + LocalMessageQuery
// {
// }
// 
// impl<T> Repo for T where
//     T: UserRepo + TeamRepo + SystemMailQuery + WorksetRepo + MemberRepo + LocalMessageQuery
// {
// }
// 
// /// Forwarding marker for [`Transactional`].
// pub struct TransactionalForward;
// 
// /// Composite of all mutable repo traits required inside a transaction.
// ///
// /// Must be `Send` because it is boxed inside [`Transactional::run_in_transaction`]
// /// and passed across `.await` boundaries on a multi-threaded Tokio runtime.
// pub trait RepoTransactional:
//     UserRepoTransactional
//     + MemberRepoTransactional
//     + MemberInvitationRepoTransactional
//     + TeamRepoTransactional
//     + WorksetRepoTransactional
//     + LocalMessageRepoTransactional
// {
// }
// 
// impl<T> RepoTransactional for T where
//     T: UserRepoTransactional
//         + MemberRepoTransactional
//         + MemberInvitationRepoTransactional
//         + TeamRepoTransactional
//         + WorksetRepoTransactional
//         + LocalMessageRepoTransactional
// {
// }
// 
// /// Transaction controller that provides ACID guarantees for multi-aggregate writes.
// ///
// /// The associated [`Repo`](Transactional::Repo) type injects a transaction-scoped
// /// connection into every mutable repository trait.
// #[async_trait]
// pub trait Transactional {
//     /// Provider that yields mutable queries with an active transaction context.
//     type Repo<'a>: RepoTransactional + Send + 'a
//     where
//         Self: 'a;
// 
//     /// Runs `f` inside a database transaction.
//     ///
//     /// If `f` returns `Ok`, the transaction is committed. If `f` returns `Err`,
//     /// the transaction is rolled back. The closure is boxed (→ `BoxFuture`) so it
//     /// can cross `.await` boundaries on a multi-threaded Tokio runtime.
//     async fn transaction_scoped<F, T>(&self, f: F) -> DomainResult<T>
//     where
//         T: Send,
//         F: for<'a> FnOnce(&'a mut Self::Repo<'a>) -> BoxFuture<'a, DomainResult<T>> + Send;
// }
// 
// /// Any type whose transaction forwarding target implements [`Transactional`]
// /// is itself [`Transactional`], delegating to the selected target.
// #[async_trait]
// impl<T> Transactional for T
// where
//     T: ForwardRef<TransactionalForward> + Send + Sync + 'static,
//     T::Target: Transactional,
// {
//     type Repo<'a>
//         = <T::Target as Transactional>::Repo<'a>
//     where
//         Self: 'a;
// 
//     async fn transaction_scoped<F, U>(&self, f: F) -> DomainResult<U>
//     where
//         U: Send,
//         F: for<'a> FnOnce(&'a mut Self::Repo<'a>) -> BoxFuture<'a, DomainResult<U>> + Send,
//     {
//         self.forward_ref().transaction_scoped(f).await
//     }
// }
