// it_07 — Workflow advance/revert and system mail notifications.
//
// Preconditions:
//   - it_00..it_06 have run. `ctx.main` is at workflow baseline (stages == 0).
//   - Assignments on main: trans_01/02/03 (translators), proof_01/02
//     (proofreaders), type_01 (typesetter), review_01 (reviewer), publish_01
//     (publisher), raw_01/02 (raw providers).
//
// Postconditions:
//   - `ctx.main.chapterId` driven through the full pipeline to publish
//     Completed.
//
// Covers test-plan: G1, G2, G3, G4, G5.
//
// Grounded pins (known deviations from test-plan):
//   - The server does NOT enforce cross-stage prerequisites. Each stage may
//     be advanced independently. "Advance publish from baseline" returns 204,
//     not 422. The pipeline order is a UI convention, not a server guard.
//   - Actually illegal transitions: advance a completed stage (422), revert
//     publish (422, hardcoded), non-enum stage (400 raw serde), path/id
//     mismatch (422/7), non-assigned user (403/4).
//   - Workflow role guards (check_workflow_role): translate Revert requires
//     PROOFREADER, typeset-redraw requires TYPESETTER/REDRAWER, publish
//     requires PUBLISHER. REVIEWERs bypass all stage checks.
//   - sadmin (ADMIN-only assignment on main) CANNOT advance any worker stage.
//   - Mails: generated by BACKGROUND task (AsyncEffectDevelop). Use
//     waitForMails to poll. ChapterWorkflowReverted produces NO mail.
//
// Status: IMPLEMENTED.

import assert from "node:assert/strict";

import { expectError, expectStatus } from "../http/assertions.js";
import type { ErrorBody } from "../http/apiClient.js";
import {
    assertMailInvariant,
    assertMailReadFilterInvariant,
    assertStagesPipelineConsistent,
} from "../http/invariants.js";
import {
    advanceStage,
    getChapter,
    listChapterWorkflowRecords,
    listSystemMails,
    markSystemMailsRead,
    revertStage,
    waitForMails,
} from "../http/fixtures.js";
import type { ChapterInfoView } from "../http/types.js";
import { PHASE, STAGE_PIPELINE, stagePhase } from "../state/stages.js";
import type { RunCtx } from "../state/runCtx.js";

export const IMPLEMENTED = true as const;

export async function runIt07Module(ctx: RunCtx): Promise<void> {
    assert.ok(ctx.main, "it_02 must have set ctx.main");

    const mainChapterId = ctx.main.chapterId;
    const sadmin = ctx.sadmin;

    const raw01 = ctx.users.get("raw_01")!;
    const trans01 = ctx.users.get("trans_01")!;
    const proof01 = ctx.users.get("proof_01")!;
    const proof02 = ctx.users.get("proof_02")!;
    const type01 = ctx.users.get("type_01")!;
    const review01 = ctx.users.get("review_01")!;
    const review02 = ctx.users.get("review_02")!;
    const publish01 = ctx.users.get("publish_01")!;

    // Earlier page uploads and unit saves intentionally auto-start workflow
    // stages. Normalize this shared fixture through the public revert API so
    // this module can exercise every transition from Pending.
    const resettableStages = [
        "raw-provide",
        "translate",
        "proofread",
        "typeset-redraw",
        "review",
    ] as const;

    for (const stage of resettableStages) {
        let chapter = await getChapter(sadmin, mainChapterId);

        while (stagePhase(chapter.stages, stage) !== PHASE.PENDING) {
            await revertStage(sadmin, mainChapterId, stage);
            chapter = await getChapter(sadmin, mainChapterId);
        }
    }

    // ---------- G1. initial workflow state ----------

    const initial = await getChapter(sadmin, mainChapterId);

    assert.equal(initial.stages, 0, "main chapter must start at workflow baseline");

    for (const stage of STAGE_PIPELINE) {
        assert.equal(stagePhase(initial.stages, stage), PHASE.PENDING, `stage ${stage} must be pending`);
    }

    assertStagesPipelineConsistent(initial);

    // ---------- G2. illegal transitions ----------

    const trans01MailsBefore = (await listSystemMails(trans01.api)).length;

    // non-enum stage -> 422 (JSON body deserialization rejection)
    expectStatus(
        await sadmin.post<ErrorBody>(`/api/v1/chapters/${mainChapterId}/stage/advance`, {
            id: mainChapterId,
            oper: "advance",
            stage: "bogus-stage",
        }),
        422,
    );

    // path/body id mismatch -> 422 code 7
    expectError(
        await sadmin.post<ErrorBody>(`/api/v1/chapters/${mainChapterId}/stage/advance`, {
            id: "not-the-path-id",
            oper: "advance",
            stage: "translate",
        }),
        422,
        7,
    );

    // non-assigned user (review_02 is NOT on main) advances -> 403/4
    expectError(
        await review02.api.post<ErrorBody>(`/api/v1/chapters/${mainChapterId}/stage/advance`, {
            id: mainChapterId,
            oper: "advance",
            stage: "raw-provide",
        }),
        403,
        4,
    );

    // wrong-role: trans_01 (TRANSLATOR-only) cannot advance publish (needs PUBLISHER) -> 403/4.
    expectError(
        await trans01.api.post<ErrorBody>(`/api/v1/chapters/${mainChapterId}/stage/advance`, {
            id: mainChapterId,
            oper: "advance",
            stage: "publish",
        }),
        403,
        4,
    );

    // revert publish -> 403/4 (role check on publish revert has no matching
    // branch in check_workflow_role, falls to _ => false → perm error)
    expectError(
        await publish01.api.post<ErrorBody>(`/api/v1/chapters/${mainChapterId}/stage/advance`, {
            id: mainChapterId,
            oper: "revert",
            stage: "publish",
        }),
        403,
        4,
    );

    // stages unchanged after failures
    const afterG2 = await getChapter(sadmin, mainChapterId);

    assert.equal(afterG2.stages, 0, "stages must not change after failed transitions");

    // no mail produced by failures (allow background a moment)
    await new Promise((resolve) => setTimeout(resolve, 150));

    const trans01MailsAfterG2 = (await listSystemMails(trans01.api)).length;

    assert.equal(
        trans01MailsAfterG2,
        trans01MailsBefore,
        "failed transitions must not produce mail",
    );

    // ---------- G3. raw-provide advance + translator mail ----------

    await advanceStage(raw01.api, mainChapterId, "raw-provide");

    const afterRaw = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(afterRaw.stages, "raw-provide"), PHASE.COMPLETED, "raw-provide completed");

    const latestWorkflowRecords = await listChapterWorkflowRecords(sadmin, mainChapterId, 0, 1);

    assert.equal(latestWorkflowRecords.length, 1, "workflow record list returns the requested page");

    const latestWorkflowRecord = latestWorkflowRecords[0]!;

    assert.equal(latestWorkflowRecord.chapter_id, mainChapterId);
    assert.equal(latestWorkflowRecord.kind, "stage-transitioned");
    assert.equal(latestWorkflowRecord.actor_user_id, raw01.userId);
    assert.equal(latestWorkflowRecord.payload.stage, "raw-provide");
    assert.equal(latestWorkflowRecord.payload.previous_phase, "pending");
    assert.equal(latestWorkflowRecord.payload.next_phase, "completed");
    assert.equal(latestWorkflowRecord.payload.origin, "manual");
    assert.ok(latestWorkflowRecord.text.length > 0, "workflow record has localized text");
    assert.ok(Number.isInteger(latestWorkflowRecord.created_at), "workflow record timestamp is integer ms");

    const nextWorkflowRecords = await listChapterWorkflowRecords(sadmin, mainChapterId, 1, 1);

    assert.equal(nextWorkflowRecords.length, 1, "workflow record pagination can read the next item");
    assert.notEqual(nextWorkflowRecords[0]!.id, latestWorkflowRecord.id, "workflow pages must not overlap");

    // advancing a completed stage -> 422/2
    expectError(
        await raw01.api.post<ErrorBody>(`/api/v1/chapters/${mainChapterId}/stage/advance`, {
            id: mainChapterId,
            oper: "advance",
            stage: "raw-provide",
        }),
        422,
        2,
    );

    // mail: raw-provide completed -> translators get unread mail (poll: async effect)
    await waitForMails(trans01.api, (n) => n > trans01MailsBefore);

    const trans01MailsAfterRaw = await listSystemMails(trans01.api);

    assert.ok(
        trans01MailsAfterRaw.length > trans01MailsBefore,
        "trans_01 must receive mail after raw-provide completed",
    );

    const newTrans01Mails = trans01MailsAfterRaw.slice(trans01MailsBefore);

    for (const mail of newTrans01Mails) {
        assert.equal(mail.read, false, "new mail must be unread");
        assert.ok(typeof mail.created_at === "number" && Number.isInteger(mail.created_at));
    }

    // proof_01 / type_01 / publish_01 do NOT receive raw-completion mail
    const proof01Mails = await listSystemMails(proof01.api);
    const type01Mails = await listSystemMails(type01.api);
    const publish01Mails = await listSystemMails(publish01.api);

    assert.equal(proof01Mails.length, 0, "proof_01 must have no mail before proofread stage");
    assert.equal(type01Mails.length, 0, "type_01 must have no mail before typeset stage");
    assert.equal(publish01Mails.length, 0, "publish_01 must have no mail before publish stage");

    await assertMailReadFilterInvariant(trans01.api);

    // ---------- G4. translate advance/revert (no mail on revert) ----------

    // translate: Pending -> Active -> Completed (2 advances by trans_01)
    await advanceStage(trans01.api, mainChapterId, "translate");

    let afterTrans = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(afterTrans.stages, "translate"), PHASE.ACTIVE);

    // NOTE: server does NOT enforce cross-stage prerequisites, so proofread
    // advance while translate is only Active would still succeed. The test
    // skips this negative; document the server's actual behaviour.
    // (If the server ever adds prerequisite checks, re-add the 422 assertion here.)

    // complete translate
    await advanceStage(trans01.api, mainChapterId, "translate");

    afterTrans = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(afterTrans.stages, "translate"), PHASE.COMPLETED);

    // translate completed -> proofreaders (proof_01/02) get mail
    await waitForMails(proof01.api, (n) => n > 0);

    const proof01MailsAfterTrans = await listSystemMails(proof01.api);

    assert.ok(proof01MailsAfterTrans.length > 0, "proof_01 must receive mail after translate completed");

    const proof02CountAfterTrans = (await listSystemMails(proof02.api)).length;

    // proofread: Active -> Completed (proof_01)
    await advanceStage(proof01.api, mainChapterId, "proofread");

    let afterProof = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(afterProof.stages, "proofread"), PHASE.ACTIVE);

    // revert proofread Active -> Pending
    await revertStage(proof01.api, mainChapterId, "proofread");

    afterProof = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(afterProof.stages, "proofread"), PHASE.PENDING, "proofread reverted to pending");

    // revert produces NO mail
    await new Promise((resolve) => setTimeout(resolve, 200));

    const proof02CountAfterRevert = (await listSystemMails(proof02.api)).length;

    assert.equal(
        proof02CountAfterRevert,
        proof02CountAfterTrans,
        "revert must not produce mail (ChapterWorkflowReverted is a no-op)",
    );

    // re-advance proofread to Completed for G5
    await advanceStage(proof01.api, mainChapterId, "proofread");
    await advanceStage(proof01.api, mainChapterId, "proofread");

    afterProof = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(afterProof.stages, "proofread"), PHASE.COMPLETED, "proofread completed for G5");

    // ---------- G5. full pipeline to publish + mark-read ----------

    // typeset-redraw: type_01 (holds TYPESETTER)
    await advanceStage(type01.api, mainChapterId, "typeset-redraw");

    let afterTypeset = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(afterTypeset.stages, "typeset-redraw"), PHASE.ACTIVE);

    await advanceStage(type01.api, mainChapterId, "typeset-redraw");

    afterTypeset = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(afterTypeset.stages, "typeset-redraw"), PHASE.COMPLETED);

    await waitForMails(review01.api, (n) => n > 0);

    // review: one-shot (review_01 holds REVIEWER → bypasses all stage checks)
    await advanceStage(review01.api, mainChapterId, "review");

    const afterReview = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(afterReview.stages, "review"), PHASE.COMPLETED);

    await waitForMails(publish01.api, (n) => n > 0);

    // advance review again -> 422/2
    expectError(
        await review01.api.post<ErrorBody>(`/api/v1/chapters/${mainChapterId}/stage/advance`, {
            id: mainChapterId,
            oper: "advance",
            stage: "review",
        }),
        422,
        2,
    );

    // publish (publish_01 holds PUBLISHER)
    await advanceStage(publish01.api, mainChapterId, "publish");

    const afterPublish = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(afterPublish.stages, "publish"), PHASE.COMPLETED, "publish completed");

    assertStagesPipelineConsistent(afterPublish);

    // advance publish again -> 422/2
    expectError(
        await publish01.api.post<ErrorBody>(`/api/v1/chapters/${mainChapterId}/stage/advance`, {
            id: mainChapterId,
            oper: "advance",
            stage: "publish",
        }),
        422,
        2,
    );

    // revert publish -> 403/4
    expectError(
        await publish01.api.post<ErrorBody>(`/api/v1/chapters/${mainChapterId}/stage/advance`, {
            id: mainChapterId,
            oper: "revert",
            stage: "publish",
        }),
        403,
        4,
    );

    // ---------- cross-user isolation + mark-read ----------

    const trans01AllMails = await listSystemMails(trans01.api);
    const proof01AllMails = await listSystemMails(proof01.api);

    const trans01Ids = new Set(trans01AllMails.map((m) => m.id));
    const proof01Ids = new Set(proof01AllMails.map((m) => m.id));

    for (const id of trans01Ids) {
        assert.ok(!proof01Ids.has(id), "trans_01 and proof_01 mail ids must be disjoint");
    }

    // mark-read trans_01's unread mails
    const trans01UnreadIds = trans01AllMails.filter((m) => !m.read).map((m) => m.id);

    if (trans01UnreadIds.length > 0) {
        await markSystemMailsRead(trans01.api, trans01UnreadIds);

        const afterMark = await listSystemMails(trans01.api, "&read=false");

        for (const m of afterMark) {
            assert.ok(!trans01UnreadIds.includes(m.id), "marked mail must not appear in unread list");
        }

        const readList = await listSystemMails(trans01.api, "&read=true");

        for (const id of trans01UnreadIds) {
            assert.ok(readList.find((m) => m.id === id), "marked mail must appear in read list");
        }
    }

    // mark another user's mail id -> 403/4
    if (proof01AllMails.length > 0) {
        const aProof01MailId = proof01AllMails[0]!.id;

        expectError(
            await trans01.api.post<ErrorBody>("/api/v1/system-mails/mark-read", {
                ids: [aProof01MailId],
            }),
            403,
            4,
        );
    }

    // idempotent mark-read -> 204
    if (trans01UnreadIds.length > 0) {
        expectStatus(
            await trans01.api.post<null>("/api/v1/system-mails/mark-read", {
                ids: trans01UnreadIds,
            }),
            204,
        );
    }

    await assertMailReadFilterInvariant(trans01.api);
    await assertMailInvariant(trans01.api);

    // final: main chapter in publish-completed state
    const finalChapter = await getChapter(sadmin, mainChapterId);

    assert.equal(stagePhase(finalChapter.stages, "publish"), PHASE.COMPLETED);

    void proof02;
    void STAGE_PIPELINE;
}
