[package]
name = "poprako-swagger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Standalone binary to generate the PopRaKo OpenAPI specification"
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
poprako-server = { path = "..", features = ["swagger"] }
serde_json.workspace = true
utoipa.workspace = true
