//! Instr DTOs for the chapter port domain.

//! Data transfer objects for chapter import/export port use cases.

#[cfg(test)]
mod tests;

use serde::de::Error as _;
use serde::{Deserialize, Deserializer};

#[cfg(feature = "swagger")]
use utoipa::ToSchema;

use crate::value::chapter_port::{
    ChapterTranslationImportMode, ExportFormatSpec, TranslationFormat,
};

/// Query selecting every format generated by one chapter export.
#[derive(Debug, Deserialize)]
#[cfg_attr(feature = "swagger", derive(ToSchema))]
pub struct ExportChapterTranslationInstr {
    /// Comma-separated formats: `poprako`, `label_plus`, or both.
    #[serde(deserialize_with = "deserialize_export_format_spec")]
    pub format: ExportFormatSpec,
}

// Converts the public comma-separated query value into a validated domain spec.
fn deserialize_export_format_spec<'de, D>(
    deserializer: D,
) -> Result<ExportFormatSpec, D::Error>
where
    D: Deserializer<'de>,
{
    let format_names = String::deserialize(deserializer)?;

    let mut label_plus = false;

    let mut poprako = false;

    for format_name in format_names.split(',') {
        //
        match format_name {
            //
            "label_plus" if !label_plus => label_plus = true,

            "poprako" if !poprako => poprako = true,

            "label_plus" | "poprako" => {
                return Err(D::Error::custom("duplicate export format"));
            }

            _ => return Err(D::Error::custom("invalid export format")),
        }
    }

    match (label_plus, poprako) {
        //
        (true, false) => Ok(ExportFormatSpec::LABEL_PLUS),

        (false, true) => Ok(ExportFormatSpec::POPRAKO),

        (true, true) => Ok(ExportFormatSpec::BOTH),

        (false, false) => {
            Err(D::Error::custom("at least one export format is required"))
        }
    }
}

/// Translation format used by chapter translation HTTP inputs.
#[derive(Debug, Clone, Copy, Deserialize)]
#[cfg_attr(feature = "swagger", derive(ToSchema))]
#[serde(rename_all = "snake_case")]
pub enum ChapterTranslationFormatInstr {
    //
    /// `LabelPlus` translation format.
    LabelPlus,

    /// `PopRaKo` native translation format.
    #[serde(rename = "poprako")]
    PopRaKo,
}

impl From<ChapterTranslationFormatInstr> for TranslationFormat {
    // Converts the transport format into the domain value.
    fn from(format: ChapterTranslationFormatInstr) -> Self {
        //
        match format {
            //
            ChapterTranslationFormatInstr::LabelPlus => Self::LabelPlus,

            ChapterTranslationFormatInstr::PopRaKo => Self::PopRaKo,
        }
    }
}

impl From<TranslationFormat> for ChapterTranslationFormatInstr {
    // Converts the domain value into the transport format.
    fn from(format: TranslationFormat) -> Self {
        //
        match format {
            //
            TranslationFormat::LabelPlus => Self::LabelPlus,

            TranslationFormat::PopRaKo => Self::PopRaKo,
        }
    }
}

/// Page-content strategy selected by a chapter translation import request.
#[derive(Debug, Clone, Copy, Deserialize)]
#[cfg_attr(feature = "swagger", derive(ToSchema))]
#[serde(rename_all = "snake_case")]
pub enum ChapterTranslationImportModeInstr {
    //
    /// Preserve pages that already contain visible Units.
    Keep,

    /// Replace every page with the Units represented by the imported source.
    Overwrite,
}

impl From<ChapterTranslationImportModeInstr> for ChapterTranslationImportMode {
    // Converts the transport import strategy into the domain value.
    fn from(mode: ChapterTranslationImportModeInstr) -> Self {
        //
        match mode {
            //
            ChapterTranslationImportModeInstr::Keep => Self::Keep,

            ChapterTranslationImportModeInstr::Overwrite => Self::Overwrite,
        }
    }
}

impl From<ChapterTranslationImportMode> for ChapterTranslationImportModeInstr {
    // Converts the domain import strategy into the transport value.
    fn from(mode: ChapterTranslationImportMode) -> Self {
        //
        match mode {
            //
            ChapterTranslationImportMode::Keep => Self::Keep,

            ChapterTranslationImportMode::Overwrite => Self::Overwrite,
        }
    }
}

/// Request body for importing chapter translations.
#[derive(Debug, Deserialize)]
#[cfg_attr(feature = "swagger", derive(ToSchema))]
pub struct ImportChapterTranslationInstr {
    //
    /// The translation format (e.g., JSON, SRT).
    pub format: ChapterTranslationFormatInstr,

    /// Page-content strategy used while applying the imported source.
    pub mode: ChapterTranslationImportModeInstr,

    /// Raw translation content string.
    pub content: String,
}
