[package]
name = "poprako-util"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Shared utility and i18n support for poprako-server"
license.workspace = true
repository.workspace = true
keywords = ["i18n", "util", "manga", "translation"]
categories = ["internationalization", "asynchronous"]
readme = false
publish.workspace = true

[lints]
workspace = true

[dependencies]
fluent-templates.workspace = true
time.workspace = true
unic-langid.workspace = true
